Manually work through the downloading and standardising steps.
This is not needed when you run: make data

In [1]:
# auto load changes to Python files
%load_ext autoreload
%autoreload 2

In [7]:
from src.data import make_dataset
import pandas as pd

In [3]:
make_dataset.download_match_data("../data/raw")

In [4]:
make_dataset.standardise_data_format("../data/raw", "../data/interim")

In [8]:
matches = pd.read_csv("../data/interim/matches_raw.csv")

# Show random sample of records for quick check
matches.sample(10)

,date,home_team,away_team,home_goals,away_goals,result,home_shots,away_shots,home_shotsOnTarget,away_shotsOnTarget,...,away_redCards,odds_interwetten_homeWin,odds_interwetten_draw,odds_interwetten_awayWin,odds_williamHill_homeWin,odds_williamHill_draw,odds_williamHill_awayWin,league,season,division
7839,2008-11-30,Portsmouth,Blackburn,3.0,2.0,H,9.0,10.0,6.0,2.0,...,0.0,1.90,3.20,3.6,2.00,3.2,3.20,E,2008,0
11283,2012-09-18,Birmingham,Bolton,2.0,1.0,H,10.0,17.0,7.0,12.0,...,0.0,2.20,3.20,3.0,2.25,3.3,3.20,E,2012,1
18197,2019-12-29,QPR,Hull,1.0,2.0,A,13.0,5.0,4.0,3.0,...,0.0,2.35,3.55,2.8,2.38,3.5,2.88,E,2019,1
6857,2007-11-24,Southampton,Blackpool,1.0,0.0,H,9.0,6.0,5.0,1.0,...,0.0,1.80,3.20,3.7,1.83,3.2,3.75,E,2007,1
6381,2007-04-06,Hull,Norwich,1.0,2.0,A,16.0,14.0,9.0,7.0,...,0.0,2.00,3.20,3.1,1.90,3.3,3.30,E,2006,1
7721,2008-10-29,Stoke,Sunderland,1.0,0.0,H,9.0,9.0,6.0,4.0,...,0.0,2.50,3.00,2.7,2.40,3.1,2.60,E,2008,0
7107,2008-01-30,West Ham,Liverpool,1.0,0.0,H,8.0,13.0,2.0,5.0,...,0.0,3.60,3.20,1.9,3.50,3.2,1.91,E,2007,0
6547,2007-08-15,Portsmouth,Man United,1.0,1.0,D,7.0,20.0,6.0,12.0,...,1.0,4.30,3.40,1.7,NaN,NaN,NaN,E,2007,0
8951,2010-02-06,Bristol City,Coventry,1.0,1.0,D,22.0,9.0,9.0,5.0,...,0.0,1.85,3.20,3.5,1.80,3.3,3.75,E,2009,1
4824,2005-09-24,Leeds,Ipswich,0.0,2.0,A,18.0,5.0,11.0,4.0,...,0.0,1.85,3.10,3.5,1.90,3.1,3.60,E,2005,1